# Generated by Django 5.1.4 on 2025-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofilemodel_email_userprofilemodel_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='position_gen',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
