# Generated by Django 5.1.4 on 2025-01-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_achievementmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='achievements',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='achievements',
            field=models.ManyToManyField(blank=True, null=True, to='users.achievementmodel'),
        ),
    ]
