# Generated by Django 5.1.4 on 2025-01-31 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofilemodel_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='certifications',
            field=models.ManyToManyField(blank=True, null=True, to='users.certificationmodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='trainings',
            field=models.ManyToManyField(blank=True, null=True, to='users.trainingprogrammodel'),
        ),
    ]
