# Generated by Django 5.1.4 on 2025-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofilemodel_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_pics'),
        ),
    ]
