# Generated by Django 5.1.4 on 2025-02-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_blogmodel_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogrammodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trainingprogrammodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trainingprogrammodel',
            name='start_date',
        ),
        migrations.AddField(
            model_name='trainingprogrammodel',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingprogrammodel',
            name='eligible_positions',
            field=models.ManyToManyField(blank=True, null=True, to='users.positionmodel'),
        ),
        migrations.AddField(
            model_name='trainingprogrammodel',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='users.skillmodel'),
        ),
        migrations.AlterField(
            model_name='positionmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainingprogrammodel',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
