# Generated by Django 5.1.4 on 2025-02-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_trainingprogrammodel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.employeemodel')),
                ('missing_skills', models.ManyToManyField(to='users.skillmodel')),
                ('recommended_training', models.ManyToManyField(to='users.trainingprogrammodel')),
            ],
        ),
    ]
