# Generated by Django 5.1.4 on 2025-02-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_skillgapanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofilemodel'),
        ),
    ]
