# Generated by Django 5.1.4 on 2025-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_skillgapanalysis_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingprogrammodel',
            name='certification',
            field=models.ManyToManyField(blank=True, null=True, to='users.certificationmodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='role',
            field=models.CharField(blank=True, choices=[('employee', 'Employee'), ('manager', 'Manager'), ('management', 'Management'), ('administrator', 'Administrator'), ('HR', 'HR')], default='employee', max_length=20, null=True),
        ),
    ]
