# Generated by Django 5.1.4 on 2025-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_jobmodel_jobapplicationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingprogrammodel',
            name='certification',
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
