# Generated by Django 5.1.4 on 2025-03-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_trainingprogrammodel_certification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='avg_performance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='avg_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
