# Generated by Django 5.1.4 on 2025-03-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofilemodel_avg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='skill_gap',
            field=models.ManyToManyField(blank=True, null=True, related_name='skillgap', to='users.skillmodel'),
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='skill', to='users.skillmodel'),
        ),
    ]
