# Generated by Django 5.1.4 on 2025-03-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_commonfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionmodel',
            name='development_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
