# Generated by Django 5.1.4 on 2025-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_positionmodel_development_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='development_plans',
            field=models.TextField(blank=True, null=True),
        ),
    ]
