# Generated by Django 5.1.4 on 2025-01-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category_spent_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='spent',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
