# Generated by Django 5.1.4 on 2025-02-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
