# Generated by Django 5.1.4 on 2025-02-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_feedbackmodel_username_feedbackmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
