# Generated by Django 5.1.4 on 2025-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feedbackmodel_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackmodel',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='feedbackmodel',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 'Poor'), ('2', 'Fair'), ('3', 'Good'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1, null=True),
        ),
    ]
