# Generated by Django 5.1.4 on 2025-03-16 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feedbackmodel_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='performance_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackmodel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
