# Generated by Django 5.1.4 on 2025-03-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_feedbackmodel_options_and_more'),
        ('users', '0020_userprofilemodel_skill_gap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainSkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('required_skills', models.ManyToManyField(to='users.skillmodel')),
            ],
        ),
    ]
